services:
    cleantalk.antispam.listener:
        class: cleantalk\antispam\event\main_listener
        arguments:
            - @template
            - @config
            - @user
            - @request
            - @dbal.conn
        tags:
            - { name: event.listener }
