;ce fichier est la config php nécessaire pour faire marcher refuges.info sur le serveur principal ou si vous utiliez php-fpm. Copiez le en .user.ini et adapté a vos besoins
upload_max_filesize = 29M
post_max_size = 31M

;Les balises php courtes (<?) ne sont plus utilisées dans le code : short_open_tag reste désactivé (valeur par défaut de php)

;Cette option permet d'activer l'affichage d'erreur de syntaxe
;display_startup_errors = 1