services:
    RefugesInfo.blockBotPosts.listener:
        class: RefugesInfo\blockBotPosts\event\listener
        tags:
            - { name: event.listener }
        arguments:
            - '@request'
            - '@user'
            - '@language'
