services:
    _defaults:
        autowire: true
        bind:
            $auth: '@auth'
            $cache: '@cache'
            $config: '@config'
            $container: '@service_container'
            $db: '@dbal.conn'
            $helper: '@controller.helper'
            $language: '@language'
            $log: '@log'
            $request: '@request'
            $template: '@template'
            $user: '@user'
            $root_path: '%core.root_path%'
            $php_ext: '%core.php_ext%'
            $sfsgroups: '@rmcgirr83.stopforumspam.core.sfsgroups'
            $sfsapi: '@rmcgirr83.stopforumspam.core.sfsapi'
            $contactadmin: '@?rmcgirr83.contactadmin.main.controller'

    rmcgirr83.stopforumspam.admin.controller:
        class: rmcgirr83\stopforumspam\controller\admin_controller

    rmcgirr83.stopforumspam.mainlistener:
        class: rmcgirr83\stopforumspam\event\main_listener
        tags:
            - { name: event.listener }

    rmcgirr83.stopforumspam.core.reporttosfs:
        class: rmcgirr83\stopforumspam\core\reporttosfs

    rmcgirr83.stopforumspam.core.report_pm_to_sfs:
        class: rmcgirr83\stopforumspam\core\report_pm_to_sfs

    rmcgirr83.stopforumspam.core.sfsgroups:
        class: rmcgirr83\stopforumspam\core\sfsgroups

    rmcgirr83.stopforumspam.core.sfsapi:
        class: rmcgirr83\stopforumspam\core\sfsapi
