/**
 * Integrated by Dominique Cavailhez (c) 2014
 * https://github.com/Dominique92/MyLeaflet
 * Generated by MagicMin: 2015-11-16 11:39:44
 */

var scripts = document.getElementsByTagName("script"),
	script = scripts[scripts.length - 1].src,
	racineSources = script.substring(0, script.lastIndexOf("/")) + "/";

document.write('<script type="text/javascript" src="'+racineSources+'leafletjs.com-leaflet-src.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Leaflet-Leaflet.fullscreen-dist-Leaflet.fullscreen.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-stefanocudini-leaflet-gps-src-leaflet-gps.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-shramov-leaflet-plugins-control-Permalink.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-MrMufflon-Leaflet.Coordinates-src-util-NumberFormatter.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-MrMufflon-Leaflet.Coordinates-src-Control.Coordinates.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-k4r573n-leaflet-control-osm-geocoder-Control.OSMGeocoder.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Dominique92-MyLeaflet-MapAutoHeight.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-kartena-Proj4Leaflet-lib-proj4-compressed.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-kartena-Proj4Leaflet-src-proj4leaflet.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Dominique92-Leaflet.MapMultiCRS-MapMultiCRS.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Dominique92-Leaflet.MapMultiCRS-OSM.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Dominique92-Leaflet.MapMultiCRS-IGN.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Dominique92-Leaflet.MapMultiCRS-IGM.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Dominique92-Leaflet.MapMultiCRS-IDEE.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Dominique92-Leaflet.MapMultiCRS-SwissTopo.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-shramov-leaflet-plugins-layer-tile-Google.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-shramov-leaflet-plugins-layer-tile-Bing.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-rob-murray-os-leaflet-src-osopenspace.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Dominique92-Leaflet.MapMultiCRS-MapMultiVendors.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-makinacorpus-Leaflet.FileLayer-leaflet.filelayer.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-mapbox-togeojson-togeojson.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-erictheise-rrose-rrose-src.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Dominique92-Leaflet.GeoJSON.Ajax-GeoJSON.Ajax.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Dominique92-MyLeaflet-MarkerPosition.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Leaflet-Leaflet.draw-dist-leaflet.draw-src.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-makinacorpus-Leaflet.GeometryUtil-dist-leaflet.geometryutil.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-makinacorpus-Leaflet.Snap-leaflet.snap.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Dominique92-MyLeaflet-PolylineEditor.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'github.com-Dominique92-MyLeaflet-locales.fr.js"></script>');