/**
 * Integrated by Dominique Cavailhez (c) 2014
 * https://github.com/Dominique92/MyLeaflet
 *
 * Credits:
 * http://leafletjs.com
 * https://github.com/Leaflet/Leaflet.fullscreen
 * https://github.com/stefanocudini/leaflet-gps
 * https://github.com/shramov/leaflet-plugins
 * https://github.com/MrMufflon/Leaflet.Coordinates
 * https://github.com/kartena/Proj4Leaflet
 * https://github.com/Dominique92/Leaflet.Map.MultiCRS
 * https://github.com/makinacorpus/Leaflet.FileLayer
 * https://github.com/mapbox/togeojson
 * https://github.com/erictheise/rrose
 * https://github.com/Leaflet/Leaflet.draw
 * https://github.com/makinacorpus/Leaflet.GeometryUtil
 * https://github.com/makinacorpus/Leaflet.Snap
 * 
 * Generated by MagicMin: 2015-01-26 09:40:20
 */

var scripts = document.getElementsByTagName("script"),
	script = scripts[scripts.length - 1].src,
	racineSources = script.substring(0, script.lastIndexOf("/")) + "/";

document.write('<script type="text/javascript" src="'+racineSources+'plugins-leaflet-leaflet-src.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-fullscreen-dist-Leaflet.fullscreen.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-gps-src-leaflet-gps.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-plugins-control-Permalink.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-coordinates-src-util-NumberFormatter.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-coordinates-src-Control.Coordinates.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-Proj4Leaflet-lib-proj4-compressed.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-Proj4Leaflet-src-proj4leaflet.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-Map.MultiCRS-MapMultiCRS.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-Map.MultiCRS-Bing.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-Map.MultiCRS-IGN.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-Map.MultiCRS-IGM.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-Map.MultiCRS-IDEE.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-Map.MultiCRS-SwissTopo.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-FileLayer-leaflet.filelayer.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-togeojson-togeojson.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-rrose-rrose-src.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'src-geoJsonAjax-geoJsonAjax.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'src-MarkerPosition-MarkerPosition.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-draw-dist-leaflet.draw-src.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-GeometryUtil-dist-leaflet.geometryutil.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'plugins-Snap-leaflet.snap.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'src-PolylineEditor.js"></script>');
document.write('<script type="text/javascript" src="'+racineSources+'src-locales.fr.js"></script>');