services:
    primehalo.primelinks.listener:
        class: primehalo\primelinks\event\main_listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
