services:
    RefugesInfo.trace.listener:
        class: RefugesInfo\trace\event\listener
        tags:
            - { name: event.listener }
        arguments:
            - '@request'
            - '@user'
            - '@auth'
            - '@language'
            - '@template'
            - '@dbal.conn'
            - '%core.root_path%'            
