services:
    RefugesInfo.couplage.listener:
        class: RefugesInfo\couplage\event\listener
        tags:
            - { name: event.listener }
        arguments:
            - '@request'
            - '@user'
            - '@language'
            - '@template'
            - '@dbal.conn'
